import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MediaContextProvider } from "../context/mediaContentContext";
import { LinkProvider } from "@/context/linkContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LinkProvider>
          <MediaContextProvider>{children}</MediaContextProvider>
        </LinkProvider>
      </body>
    </html>
  );
}
